[build.environment]
  NPM_FLAGS = "--include=dev"

[build]
  command = "rm -rf node_modules && npm ci --include=dev && npx vite build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://car-rental-api-pp6g.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
