[build.environment]
  NPM_FLAGS = "--include=dev --legacy-peer-deps"
  NODE_VERSION = "18"

[build]
  command = "rm -f package-lock.json && npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://car-rental-api-pp6g.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
