services:
  - type: web
    name: rental-system-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://car-rental-api-pp6g.onrender.com/api
