services:
  - type: web
    name: rental-system
    env: static
    buildCommand: npm ci && npx vite build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://car-rental-api-pp6g.onrender.com/api
